import "./globals.css";
import { Inter } from "next/font/google";
import Footer from "../../components/Footer";
import Header from "../../components/Header";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "arts-olympiad",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <header>
          <Header/>
        </header>

        {children}

        <footer>
          <Footer/>
        </footer>

      </body>
    </html>
  );
}
