import './globals.css'
import { Inter } from 'next/font/google'
import Link from 'next/link'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'arts-olympiad',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <header className="header">

          <ul className="navigation">
            <Link href="/"><li className="logo"></li></Link>
            <button className="secondary-button">Share</button> {/* will be a component*/}
            <Link href="/Home"><li>Home</li></Link>
            <Link href="/Gallery"><li>Gallery</li></Link>
            <Link href="/Purpose"><li>Purpose</li></Link>
            <Link href="/About"><li>About</li></Link>
            <Link href="/Team"><li>Team</li></Link>
            <button className="main-button">Upload</button>
            <button className="main-button">Vote</button>
            <li className="triple-stack">TODO</li> {/* tripple stack mobile component*/}
          </ul>

        </header>

        {children}

        <footer>
          {/* code here */}
        </footer>

      </body>
    </html>
  )
}
